server:
  addr: ":8090"
  read_timeout: 10s
  write_timeout: 10s

log:
  level: "debug"
  output: "console" # console/file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backup: 10
  max_age: 30 # å¤©

db:
  driver: "mysql"
  dsn: "root:mfkfnmqj@tcp(127.0.0.1:3306)/chat_s3?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 100
  max_idle_conns: 20
  conn_max_lifetime: 3600s

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 100
