server:
  addr: ":8090"
  read_timeout: 10s
  write_timeout: 10s

log:
  level: "debug"
  output: "console" # console/file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backup: 10
  max_age: 30 # å¤©

redis:
  addr: "redis:6379"
  password: ""
  db: 0
  pool_size: 100
